### ISSUE TITLE
--mount-root option broken in v >= 0.2.45

### ISSUE THREAD

**Issue by jscn** [infoxchange/docker-forklift#97]
The `--mount-root` option no longer works for me in version `0.2.45` and up. If I downgrade to `0.2.44` then the following command runs fine:

```
$ forklift 273695c4789e sshd --mount-root ~/docker/fs/
mount: /dev/mapper/docker-252:0-4468428-0de707309f72cd745fd4340ad11852346ee7021cfc585de83ff97bffec093baf already mounted or /var/lib/docker/devicemapper/mnt/0de707309f72cd745fd4340ad11852346ee7021cfc585de83ff97bffec093baf/ busy
Traceback (most recent call last):
  File "/usr/local/bin/forklift", line 9, in <module>
    load_entry_point('docker-forklift==0.2.45', 'console_scripts', 'forklift')()
  File "/usr/local/lib/python3.4/dist-packages/forklift/__init__.py", line 338, in main
    return Forklift(sys.argv).main()
  File "/usr/local/lib/python3.4/dist-packages/forklift/__init__.py", line 319, in main
    return driver.run(*command)
  File "/usr/local/lib/python3.4/dist-packages/forklift/drivers.py", line 240, in run
    return self.run_sshd()
  File "/usr/local/lib/python3.4/dist-packages/forklift/drivers.py", line 446, in run_sshd
    self.mount_root(container)
  File "/usr/local/lib/python3.4/dist-packages/forklift/drivers.py", line 365, in mount_root
    container_path])
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'mount', '-o', 'context=""', '/dev/mapper/docker-252:0-4468428-0de707309f72cd745fd4340ad11852346ee7021cfc585de83ff97bffec093baf', '/var/lib/docker/devicemapper/mnt/0de707309f72cd745fd4340ad11852346ee7021cfc585de83ff97bffec093baf/']' returned non-zero exit status 32
```

Ubuntu 14.04.3 LTS
Docker version 1.7.1, build 786b29d
Forklift Version: 0.2.45

**Comment by danni** [comment]
Hmm. I'm guessing you don't have SELinux and thus we need to omit the 'context' parameter.

**Comment by jscn** [comment]
I do not SELinux. I gave this a quick shot locally by removing the `context` argument but I'm still getting the error:

```
$ forklift 3985400cef6c sshd --mount-root ~/docker/fs/
mount: /dev/mapper/docker-252:0-4468428-56d47997d635cf7fed30b26f5e98df19cabea5b3215dc234e1c9a1f0a062206e already mounted or /var/lib/docker/devicemapper/mnt/56d47997d635cf7fed30b26f5e98df19cabea5b3215dc234e1c9a1f0a062206e/ busy
Traceback (most recent call last):
  File "/usr/local/bin/forklift", line 9, in <module>
    load_entry_point('docker-forklift==0.2.47', 'console_scripts', 'forklift')()
  File "/usr/local/lib/python3.4/dist-packages/forklift/__init__.py", line 338, in main
    return Forklift(sys.argv).main()
  File "/usr/local/lib/python3.4/dist-packages/forklift/__init__.py", line 319, in main
    return driver.run(*command)
  File "/usr/local/lib/python3.4/dist-packages/forklift/drivers.py", line 240, in run
    return self.run_sshd()
  File "/usr/local/lib/python3.4/dist-packages/forklift/drivers.py", line 450, in run_sshd
    self.mount_root(container)
  File "/usr/local/lib/python3.4/dist-packages/forklift/drivers.py", line 369, in mount_root
    subprocess.check_call(args)
  File "/usr/lib/python3.4/subprocess.py", line 557, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'mount', '/dev/mapper/docker-252:0-4468428-56d47997d635cf7fed30b26f5e98df19cabea5b3215dc234e1c9a1f0a062206e', '/var/lib/docker/devicemapper/mnt/56d47997d635cf7fed30b26f5e98df19cabea5b3215dc234e1c9a1f0a062206e/']' returned non-zero exit status 32
```
